name: Pipeline CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2
      - name: Configurer JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'  # Add this line here
      - name: Construire avec Maven
        run: mvn clean install
      - name: Exécuter les tests unitaires
        run: mvn test
      - name: Construire l'image Docker
        run: |
          docker build -t votre-nom-image .
